CREATE TABLE USERINFO
(
  USER_SEQ INTEGER PRIMARY KEY NOT NULL,
  ADDR     VARCHAR(255),
  HEIGHT   DOUBLE              NOT NULL,
  WEIGHT   DOUBLE              NOT NULL,
  AGE     DOUBLE

);
CREATE TABLE USER
(
PASSWORD      VARCHAR(255),
USER_SEQ      INTEGER  NOT NULL,
USER_INFO_SEQ INTEGER             NOT NULL,
NAME          VARCHAR(255),
PRIMARY KEY(USER_SEQ,USER_INFO_SEQ ),
CONSTRAINT FKS90DMX870C8AYEY1NH7WGVTC4 FOREIGN KEY (USER_SEQ) REFERENCES USERINFO (USER_SEQ)
);

